[package]
name = "hubris"
version = "0.1.0"
authors = ["Jared Roesch <roeschinc@gmail.com>"]
build = "build.rs"

[lib]
name = "hubris"
path = "src/hubris/lib.rs"

[[bin]]
name = "hubris"
path = "src/bin/hubris.rs"

[dependencies.hubris_parser]
path = "src/hubris_parser"

[dependencies.lalrpop-util]
version = "0.8.0"

[build-dependencies.lalrpop]
version = "0.8.0"

[dependencies]
llvm-sys = "*"
log = "*"
env_logger = "*"
gcc = "*"
docopt = "0.6"
iron = "*"
rustc-serialize = "0.3"
serde = "*"
serde_json = "*"
serde_macros = "*"
term = "*"
